apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/data/keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:   # 更改文件夹权限
      - name: volume-permission
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /opt/keycloak/data"]
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data     
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.1
        args: ["start-dev","--import-realm"]
        ports:
        - containerPort: 8080
        env:
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: cotrip-kv-secret
                key: KEYCLOAK_ADMIN_USERNAME
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cotrip-kv-secret
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KEYCLOAK_IMPORT
            value: "/config/keycloak-config.json"
          - name: KC_STRICT_HOSTNAME
            value: "false"
          - name: KC_PROXY
            value: "edge"
        ports:
          - name: http
            containerPort: 8080

        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        volumeMounts:
        - name: keycloak-config
          mountPath: "/config"
          readOnly: true
        - name: keycloak-config
          mountPath: "/opt/keycloak/data/import"
          readOnly: true
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
      - name: keycloak-config
        secret:
          secretName: keycloak-config 
         
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8080
