apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotrip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cotrip
  template:
    metadata:
      labels:
        app: cotrip
    spec:
      containers:
      - name: cotrip
        image: registry.cn-hangzhou.aliyuncs.com/leansd/cotrip:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.profiles.active
          value: default
        - name: server.port
          value: '8080'
        - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
          value: 'http://keycloak:8089/realms/leansd'
        - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
          value: 'http://keycloak:8089/realms/leansd/protocol/openid-connect/certs'
      imagePullSecrets:
      - name: aliyun-registry-key
