apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotrip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cotrip
  template:
    metadata:
      labels:
        app: cotrip
    spec:
      containers:
      - name: cotrip
        image: registry.cn-hangzhou.aliyuncs.com/leansd/cotrip:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.profiles.active
          value: dev
        - name: server.port
          value: '8080'
      imagePullSecrets:
      - name: aliyun-registry-key
