apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    alicloud-pvname: keycloak-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ossplugin.csi.alibabacloud.com
    volumeHandle: keycloak-pv
    volumeAttributes:
      bucket: "cotrip"
      url: "oss-cn-beijing.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
      path: "/"
      akId: "LTAI5tF5qxkWSSPHps2vc57X"
      akSecret: "U8Bt3NCqHkUuOfIYXahzBbDUNEiGQw"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      alicloud-pvname: keycloak-pv

