apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: template
commonAnnotations:
  contact: lxbzmy@gmail.com

#buildMetadata:
# - managedByLabel
#- originAnnotations
#- transformerAnnotations

namespace: leansd
resources:
- config/
- keycloak.yaml

